AltimateAI/vscode-dbt-power-user

src/commands/runModel.ts
Quick changes to add the ability to:
1. Run the `dbt` command in the current terminal or in a new one (to fix the last comments in https://github.com/innoverio/vscode-dbt-power-user/issues/24)
2. Modify the default `dbt run` command by potentially adding flags for example (to fix https://github.com/innoverio/vscode-dbt-power-user/issues/13)
In order to work, people will need to add entries in the `settings.json` file of their workspace:
Here is an example of values:
```
"innoverio-vscode-dbt-power-user":{
"setting":{
"current_terminal" : true,
"dbt_command" : "dbt run --full-refresh"
}
}
```
For now, those parameters show with a message saying "Unknown Configuration Setting" and I think that changes will be required in `package.json` to remove the warning, but it is working anyway.
=> Adding parameters to the extension

src/manifest/parsers/graphParser.ts
Make the extension work with models that contain dots, as suggested in this [dbt post](https://discourse.getdbt.com/t/extracting-schema-and-model-names-from-the-filename/575)
=> Support dots in model names

src/dbt_client/index.ts
The extension was hanging for me on DBT version 0.21.0, so I updated the regexes to allow for double digit version numbers.
=> Update regex to allow for double digit version numbers

package.json
Made the ctrl+enter shortcut work only while in the editor
=> Restrict execute dbt SQl to only execute when the editor has focus

src/manifest/parsers/docParser.ts, src/manifest/parsers/index.ts, src/manifest/parsers/macroParser.ts, src/manifest/parsers/nodeParser.ts, src/manifest/parsers/sourceParser.ts, src/manifest/parsers/testParser.ts
After the update of DBT Core to 1.4.0 there is a change that affects the parsing of the manifest, the property of the nodes called `root_path` [is not existing anymore](https://docs.getdbt.com/guides/migration/versions/upgrading-to-v1.4)
=> [Fixed] Adapt manifest parse to not use deprecated root_path

src/manifest/dbtProject.ts
When generating source models, if the columns contain weird characters like `'`, the model cannot be run.
Surrounding the column names with double quotes resolves this issue.
I have no clue how vscode plugins work, so I didn't run this code yet. Please review carefully.
=> Surround source model columns with double quotes

src/document_formatting_edit_provider/dbtDocumentFormattingEditProvider.ts
This resolves the [discussion](https://github.com/innoverio/vscode-dbt-power-user/discussions/315#discussioncomment-4918534)
The suggested change is:
Reflecting normal (replace) changes with a _**delete line first and then insert**_ approach rather than using vscode's `TextEdit.replace()` since the weird behavior on formatting seems because of the replace changes. I don't have experience on vscode's API. So, this the only change that I can suggest right now. Any contribution is much appreciated.
=> Reflect replace edits as delete & insert

package.json, src/manifest/dbtProject.ts, src/manifest/pythonEnvironment.ts, src/utils.ts
Expand `${workspaceFolder}` and `${env:VARIABLE}` placeholders in the settings for `dbt.profilesDirOverride` and `dbtPythonPathOverride` using the logic previously only used for environment variable settings. This address #237 and #199.
As was discussed in those issues, variable substitution is a common issue with vscode extensions and the recommended workaround was to use paths relative to the workspace directory. But with version 0.11.4 installed from the vscode marketplace, this did not work for me anymore - only absolute paths worked.
Merging this feature would be a great help for Meltano integration because settings.json can then be added to the repository, ensuring a consistent experience for all developers (see https://github.com/meltano/meltano/issues/2811)
- had to bump engine …
=> Subsitute variables in settings

src/document_formatting_edit_provider/dbtDocumentFormattingEditProvider.ts
`parseDiff` reads sqlfmt's `\ No newline at end of file` diff output as a delete change. So, this deceptive delete change should be skipped. I attempted to handle this by adding an edge case to the expression. A sample `changes` list from `parseDiff` below:
```typescript
changes: [
// ...
{
type: "del",
del: true,
ln: 33,
content: "-where json:EventCode is not null"
},
{
type: "del",
del: true,
ln1: undefined,
ln2: undefined,
ln: 33,
content: "\\ No newline at end of file"
}
// ...
]
```
=> Skip faulty delete change for no newline at EOF

src/lineage_provider/modelGraphViewPanel.ts
The problem was that the lineage view was not loading the first time that the extension was loading, requiring the user to change betwen files to reload it
=> [Fixed] Lineage view not loading the first time

dbt_integration.py, package.json, src/manifest/dbtProject.ts, src/manifest/parsers/index.ts
resolves #444 
Creates a new configuration option for overriding the target path. This should help for folks that have Jinja in their dbt_project file `target-path` value and for situations where you want a separate manifest that the extension manages vs the manifest you use for development.
I tested this against the dbt `jaffle_shop` demo repo. If you set the path to `"dbt.targetPathOverride": "${workspaceFolder}/target_2",` the extension will read and write to the `target_2` dir. Confirmed in the debug output that `Using target path /Users/jasonb/code/jaffle_shop/target_2` showed up.
=> Add the `targetPathOverride` config value

src/document_formatting_edit_provider/dbtDocumentFormattingEditProvider.ts
In the previous code, an empty string (`[""]`) is passed as `sqlFmtAdditionalParamsSetting` when `sqlFmtAdditionalParams` has no settings.
This causes sqlfmt to stop working in my environment.
According to https://docs.sqlfmt.com/getting-started/configuring-sqlfmt#configuration-reference, an empty string is never passed as an option in sqlfmt. So, empty strings should not be included in `sqlFmtAdditionalParamsSetting`.
I have not been able to determine why sqlfmt was not working when an empty string was passed. My apologies for this.
=> Fix bug for empty sqlFmtAdditionalParams

src/document_formatting_edit_provider/dbtDocumentFormattingEditProvider.ts
With this PR, we're enhancing the functionality of the DbtDocumentFormattingEditProvider class to support variable expansion, such as ${workspaceFolder}, when setting up the sqlFmtPath. This will provide users with more flexibility and better integration with diverse workspace configurations :)
=> Support Variable Expansion in sqlFmtPath Setting

package.json, src/dbtPowerUserExtension.ts, src/hover_provider/index.ts, src/hover_provider/modelHoverProvider.ts, src/hover_provider/sourceDefinitionProvider.ts, src/hover_provider/sourceHoverProvider.ts
Starts to resolve #525
This is a real copy paste paint by numbers kind of job. I'm modeling all this code on how the definition provider is done. There is likely some code that is worth abstracting here and the hover itself isn't the prettiest but I thought this was a good start. Happy to keep iterating on this if folks want a more full featured version of this.
Additional features this could use:
1. Parse tests from the manifest for the refs so you can show tests
2. Parse descriptions/columns/types from sources
3. Do a macro hover provider too.
4. Better styling on the markdown
I tested this on a jaffle shop repo. Here are some screenshots:
=> feat: hover providers for refs and sources

docs_edit_panel/main.js
resolves #595 
I have tested this on jaffle shop. Changed case of payments_id column of stg_payments model and it didn't clear the description as described in the issue.
=> fix: column comparision issue

src/domain.ts, src/hover_provider/modelHoverProvider.ts, src/hover_provider/sourceHoverProvider.ts, src/hover_provider/utils.ts, src/manifest/parsers/nodeParser.ts, src/manifest/parsers/sourceParser.ts
Resolves half of #594 
Parsing the descriptions and columns for sources and adding that info into the Hover provider for sources. I'm just pattern matching what is happening in the model parsing and it all lined up. 
Now the description and columns show up in the source hover box too:
Macros has similar metadata (descriptions and even function arguments/types -- see [macro properties dbt docs](https://docs.getdbt.com/reference/macro-properties)) but even the most popular packages like dbt_utils don't fill out those properties. I think adding that would be a good follow up. It might encourage package developers to actually fill out the properties.
=> Add descriptions and column metadata to the source metadata

README.md, package.json, src/manifest/dbtWorkspaceFolder.ts
Adds an optional folder allowlist configuration.
Introduce an 'allowlist' feature to enable users to specify project folders explicitly, ensuring that only projects within these folders are included in the build process. This provides greater control over project compilation and improves workspace performance by preventing the accidental compilation of unrelated projects.
With our monorepo structure, we are unable to use the extension because it attempts to spin up several hundred projects at once causing device OOM's and reboots. Adding an allowlist will help us to specifically target the projects we work on.
=> Adding an allow list configuration option

src/commandProcessExecution.ts, src/dbt_client/index.ts, src/document_formatting_edit_provider/dbtDocumentFormattingEditProvider.ts
Slack: https://getdbt.slack.com/archives/C05KPDGRMDW/p1696953977216509
With the formatOnSave option turned on, the first time I pressed save the file it doesn't get formatted but it does in the second save.
The existing implementation passes the file path to `sqlfmt` rather than the changed content. Since the file is not yet saved when I hit the first save, `sqlfmt` reads the previous version of the file and no formatting occurs, and the unformatted new content is saved to the file. And when I hit the second save, finally the file gets formatted because `sqlfmt` now can read the unformatted content from the file.
Pass modified content of the file to `sqlfmt` instead of the file path
- CommandProcessExecution.complete is extended to get a string and pass it into spawned process as stdin.
=> Pass changed document text to sqlfmt through stdin instead of file path

README.md, package.json, src/dbt_client/dbtCommandFactory.ts
Hi!
I am using the custom dbt runner for my dbt packages. I need some way to make it configurable. I want to try this approach:
1. Add a parameter containing a Python import row with the custom runner to settings. 
2. Use the parameter in the method that creates the dbt command(`dbtCommand`)
For an example, I have module `my_custom_runner`:
```
from dbt.cli.main import dbtRunner
class dbtCustomRunner(dbtRunner):
def invoke(self, *args, **kwargs):
print("Hello from overwritten runner!")
print("Staring invoke...")
return dbtRunner.invoke(self, *args, **kwargs)
print("Invoke finished!")
```
`dbt.dbtCustomRunnerImport` = `from my_custom_runner import dbtCustomRunner as dbtRunner`
Then the extension will use the overwritten custom runner from my package.
Example:
resolves #565
=> Add custom dbt runner import

src/dbt_client/dbtCommandFactory.ts, src/manifest/dbtProject.ts
if profiles directory override has a trailing slash, that can act as an escape char (windows style paths eg: C:\Users\Username\.dbt\ )
additional housekeeping - update command string that gets displayed when running a dbt command.
resolves #639
=> fix: windows style ending slash causes python error

dbt_integration.py
resolves #609 
The compile function accept the raw sql as argument. lru cache uses parameters as the key for cache and since upstream updates or different macro outputs will not change the raw/jinja sql, it will not recompile. 
This change WILL affect performance in the sense that rerunning the same query multiple times in the same session will be slower (eg you are looking at preview and decide to execute it, it will be marginally slower than before). If this is a significant problem, we can reintroduce cache with a better invalidation system. til then accuracy of the previews/dispatched sql is more important.
=> fix: remove caching for compiled sql

src/commandProcessExecution.ts, src/dbt_client/dbtTerminal.ts, src/manifest/modules/dbtProjectLog.ts, src/utils.ts
remove ansi colors added by dbt output.
The terminal seems to be able to render ansi colors but the outputs panels dont support custom ansi colors yet - only lang highlights. There are open issues in vscode github but does not look like they will incorporate the requests - so removing colors from the output lines for now.
also removing the additional endlines that appear in outputs panel. again, terminal seems to handle these extras well outputs looks like a basic log dump that renders everything. currently it is unusable with the weird chars and extra endlines so trying to fix that a bit.. adding images below:
new:
old:
=> fix: outputs panel colors and extra endlines

dbt_integration.py, src/commands/walkthroughCommands.ts, src/manifest/dbtProject.ts
fixes: #601 
Scenarios tested: 
- switch from a valid target to another valid target - in both cases project should reload the new credentials/adapter type as specified in the target.
- switch from an invalid target (project still loaded) to a valid one 
- switch from an invalid profile (project loaded without configs) to a valid profile and a valid target
Scenarios not tested (and probably not supported)
- switching to an adapter type that is not installed in the environment
- dbt was not installed before and now it is
- changing profiles root directory (either by using extension settings or using dbt defaults)
=> feat: allow users to change profiles.yml without having to reload window

package.json, query_panel/index.html, query_panel/main.js, src/manifest/dbtProject.ts, src/webview_provider/queryResultPanel.ts
This PR throws error if users enters a 0 or negative value in the query limit, both in query panel and also extension settings
resolves: https://github.com/AltimateAI/vscode-dbt-power-user/issues/756
=> fix: throw error when query limit is not positive

src/dbt_client/index.ts, src/manifest/pythonEnvironment.ts
In our project, we use [multi-root-workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces).
And we have installed `dbt` on 'dbt' workspace folder, not installed on workspace root.
In the current implementation, `dbt-power-user` searchs `dbt` of workspace root, so editor raises error in `dbt_project.yml`.
the error message of my editor is here:
Ideally, I would like it to use the python paths in the current edit workspace folder, but this feature is too large, so I have changed the search logic to python environments when `dbt` is not installed in workspace root.
=> fix: support dbt path resolver in multi root workspace.

dbt_integration.py
We are seeing exceptions related to loading of the ALTIMATE_PACKAGES_PATH. To resolve, we are moving it inside the function where the contextmanager loads it. It is wrapped in a try catch block so even if it fails other functionalities are not affected
=> fix: safe creation of packages path

src/dbt_client/dbtTerminal.ts, src/dbt_client/exception.ts, src/webview_provider/docsEditPanel.ts
WIP
fix: logging service
WIP
WIP
feat: combined logging and terminal
feat: added strip ansi
feat: optional telemetry
WIP
fix: as per comments
WIP
=> feat: added logging service

query_panel/main.js
- Fixes integer overflow in query results panel new UI
- perspective.js does not handle int64 and workaround suggested is to convert the int to float and use without precision. https://github.com/finos/perspective/issues/1346
- So for any integer type in schema, we will use float type with 0 precision digits and without grouping to avoid thousands separator
=> fix: use float instead of int in query results to avoid overflow

src/webview_provider/docsEditPanel.ts, webview_panels/src/modules/dataPilot/components/NewGenerationResults.tsx, webview_panels/src/modules/documentationEditor/components/docGenerator/BulkGenerateButton.tsx, webview_panels/src/uiCore/theme.scss
Fix for: https://altimateai.atlassian.net/browse/AI-1514
- When user requests to generate docs for all columns, sync with db first and then generate with new columns
- also fixed minor css issue to show proper color for input/textarea placeholder text
=> fix: sync columns before generate all in new doc editor

query_panel/style.css
Horizontal scrollbar in query results panel is not visible and make it harder to see the columns out of viewport
Horizontal scrollbar is already available in perspective viewer table but the height is limited by the border. In this PR, border width is reduced to make the scrollbar more prominent
- open query results panel and run a query which can return more columns in result
- horizontal scrollbar should be visible as in screenshot and user should be able to scroll
=> fix: make horizontal scrollbar visible in query panel

webview_panels/src/modules/dataPilot/components/queryAnalysis/QueryAnalysis.tsx
- Shows warning message in datapilot if selected code is more than 10 lines in query change feature
- resolves https://altimateai.atlassian.net/browse/AI-1533
=> fix: show warning message if query change has more than 10 lines

src/dbt_client/dbtTerminal.ts
Problem: In the current logging service, if we need to pass extra arguments/meta data for logs, use JSON.stringify and add to the log message. This will be difficult to read and parse later.
Solution: Use the same parameters as outputChannel to accept arbitrary array of data and write to channel.
=> fix: add logging with extra args

src/document_formatting_edit_provider/dbtDocumentFormattingEditProvider.ts
Resolves #856
As (partly) explained in #856, the issue is that, taking any file:
- that is "unformatted enough" i.e. that it has several "chunks" output by sqlfmt
- that "deletes enough lines" (so that the already nicely-formatted text between 2 "chunks" should be moved too)
The file will be formatted wrongly to the extend that the SQL code is not valid anymore.
Example: See related issue for a file that would get corrupted before this PR.
Code walkthrough:
Option 1: Let sqlfmt do the job entirely instead of parsing its results (faster and simpler). https://github.com/AltimateAI/vscode-dbt-power-user/pull/930
Option 2 (this PR): Parse sqlfmt results and create 'TextEdit' changes for each row to change and each row in-between chunks:
- I added a "replace" function since this delete/insert …
=> fix: wrong formatting (#856)

webview_panels/src/modules/documentationEditor/components/saveDocumentation/SaveDocumentation.tsx, webview_panels/src/modules/documentationEditor/styles.module.scss
- In new documentation editor, if schema.yml file is missing, file selector icon is not visible
- on clicking save, we show error
- This PR solves the UX issue to show file selector button and set default option as selecting an existing file
=> fix: documentations save flow

src/manifest/pythonEnvironment.ts
This fix ensures invalid config are not used by the extension resulting in inconsistent behaviour in the terminal vs the extension.
Can be simulated by putting this in .vscode/settings.json
```
"terminal.integrated.env.tst": {
"DBT_PROFILES_DIR": "~/.dbt/profiles.yml"
} 
```
=> Fix terminal integrated env

src/document_formatting_edit_provider/dbtDocumentFormattingEditProvider.ts
Earlier error was thrown as `string` which can directly be used as diffOutput. But now since error is thrown as `Error`, need to pass the message.
=> fix: sql formatting

src/altimate.ts, src/dbt_client/dbtCoreIntegration.ts, src/webview_provider/insightsPanel.ts, webview_panels/src/modules/defer/DeferToProduction.tsx, webview_panels/src/modules/defer/ManifestSelection.tsx, webview_panels/src/modules/defer/defer.module.scss, webview_panels/src/modules/defer/types.ts, webview_panels/src/uiCore/components/iconButton/IconButton.tsx, webview_panels/src/uiCore/index.ts
- If user removes the altimate key, on every build action he’s getting a notification “To use this feature …”, this is confusing the user might not know this is because defer to prod is enabled.
- If user removes the altimate key, he keeps getting multiple notifications, I think it is because of us fetching the integrations. I think we should only fetch them once and provide a refresh button.
- updated error message
- added caching for project integrations and introduced refresh button
https://www.awesomescreenshot.com/video/25630595?key=79d8573f2fa0544b7ef418d80de83eaa
- In a multi project workspace, enable defer to prod feature
- Add a project integration
- Remove the alimate key/instance name from settings
- Switch between different models in different projects
- Verify the …
=> fix: defer to prod notification issues

src/quickpick/sqlQuickPick.ts
QuickPick for bigquery does not work due to not passing argument
By default pass true
- Use Cost estimator using quick pick on a  bigquery dbt project
=> fix: bigquery sql quick pickl

webview_panels/src/modules/documentationEditor/DocumentationEditor.tsx, webview_panels/src/modules/documentationEditor/components/docGenerator/DocGeneratorColumn.tsx
- In new doc gen editor, when a column/model does not have any description and user generates documentation, save button is not showing
- fixed the state update dispatch to show save button in these cases
NA
- Open a model without description for model and column
- Use new doc editor version
- Generate desc for column/model
- Save should show and on save, should save to yaml
=> fix: show save on first generation in doc editor

src/dbt_client/dbtCoreIntegration.ts
For local mode in defer to prod feature, dont send event to backend to track the run
Removed tracking event and added telemetry event
NA
- Enable defer to prod with local integration
- Run a dbt command like run,test,build
- Should not send event to backend but to telemetry
=> fix: send defer event to backend only for remote

.vscode/launch.json, CONTRIBUTING.md, webview_panels/package.json, webview_panels/vite.config.ts
- recently added [debug](https://github.com/AltimateAI/vscode-dbt-power-user/issues/946) config for development is not working reliable. It stops watch command abruptly
- also, the debug source code is not reflecting the updated code
- icons from codicons are not showing up
- update `launch` config to use `webpack` as before
- added new `debug extension` config to use this new flow.
NA
- Click `Launch extension` / `debug extension`
=> fix: debug launch config

src/statusbar/deferToProductionStatusBar.ts, src/webview_provider/altimateWebviewProvider.ts, src/webview_provider/insightsPanel.ts
- Logs are polluted with unnecessary error logs
- Sending message to webview panel is not consolidated in insights page
- Converted few errors to debug/warn as it is not a real error
- moved all `postMessage` api to `sendResponseToWebview` api
NA
- Regression for defer to prod feature
=> chore: send response to webview cleanup and make errors to warning

src/dbt_client/dbtCloudIntegration.ts, src/dbt_client/dbtCoreIntegration.ts, src/domain.ts, src/manifest/dbtProject.ts, src/manifest/parsers/macroParser.ts, src/manifest/parsers/testParser.ts, src/services/dbtTestsService.ts, src/services/docGenService.ts, src/webview_provider/docsEditPanel.ts, src/webview_provider/newDocsGenPanel.ts, webview_panels/src/modules/documentationEditor/components/tests/DbtTestCode.tsx, webview_panels/src/modules/documentationEditor/components/tests/DisplayTestDetails.tsx, webview_panels/src/modules/documentationEditor/components/tests/TestDetails.tsx, webview_panels/src/modules/documentationEditor/styles.module.scss, webview_panels/src/uiCore/components/codeblock/index.tsx
1. In the new tests section in documentation editor, if a model/column has manually created macro test with below sample code in `macros` directory, the sql code is not display in right side panel, when clicking the macro name.
```
{% test positive_value(model, column_name) %}
SELECT
*
FROM
{{ model }}
WHERE
{{ column_name}} < 1
{% endtest %}
```
2. If a test for column/model has extra config like [this example ](https://docs.getdbt.com/reference/resource-configs/where#examples), show these extra config in right side panel
1. Modified the code to add the test macros also from `macros` directory into `macroMetamap` and use the information to find the file path for generating tests data
2. Modified `getTestCode` command to get sql source and also extra configs from schema.yml
Before …
=> fix: show test macro code in tests editor

new_lineage_panel/src/service_utils.ts
After cancelling column lineage once, unable to perform column lineage at all.
cancel state was not getting reset. Fix it
=> fix: cancel state not resetting

new_lineage_panel/src/CustomNodes.tsx, new_lineage_panel/src/components/Column.tsx, src/commands/runModel.ts, src/domain.ts, src/manifest/dbtProject.ts, src/manifest/event/manifestCacheChangedEvent.ts, src/manifest/parsers/graphParser.ts, src/manifest/parsers/index.ts, src/manifest/parsers/metricParser.ts, src/treeview_provider/modelTreeviewProvider.ts, src/webview_provider/newLineagePanel.ts
Support metrics in lineage panel and tree view
Only semantic_model is supported
Currently incorrectly shown as view @AdiGajbhiye 
Add metrics to your project for example:
```
semantic_models:
#The name of the semantic model.
- name: orders
defaults:
agg_time_dimension: ordered_at
description: |
Order fact table. This table is at the order grain with one row per order. 
#The name of the dbt model and schema
model: ref('orders')
```
=> Support metrics

src/manifest/dbtProject.ts, webview_panels/src/modules/dataPilot/components/queryAnalysis/components/QueryTranslateDialectSelects.tsx
- While trying to translate query, it was difficult to find right adapter
- Add debug log for package version for debugging
- sorted the translate dialect options
- debug log for package version
- In query translation, check the options shown in translate dropdowns. Should be sorted in alphabetical order
- If dbt utils or expectations is installed in the project, while making translate api call, this should show in debug log
=> improve: sort translate options and debug log

src/webview_provider/datapilotPanel.ts, webview_panels/src/modules/dataPilot/components/queryAnalysis/useQueryAnalysisAction.ts
- DataPilot explain functionality is not giving text box to ask additional questions.
(Also for a few seconds) - valid SQL model needs to be open in editor message flashes. Also, the text shows for this SQL query instead of dbt model when explanation is printed. 
- get follow up questions api was expecting a valid file path which was not passed from webview properly. Added the file path from where the conversation is initiated
NA
- Open a valid model
- right click -> datapilot -> explain
- Should see valid explanation and follow up questions if available
=> fix: query explain unnecessary errors

webview_panels/src/modules/documentationEditor/components/saveDocumentation/SaveDocumentation.tsx, webview_panels/src/modules/documentationEditor/components/tests/DisplayTestDetails.tsx, webview_panels/src/modules/documentationEditor/components/tests/EntityWithTests.tsx
Issues:
1. 
```
when I am working on a branch and have edited files in multiple folders, each with their own models.yml file I get the following.
1. First file i try to document with the documentation editor, let's say it is in the orders folder, so i try to save its documentation into existing file, select the orders_models.yml file, and that works great
2. i try to document another file, in the customers folder lets say. if i pick existing file, it doesn't ask me to pick a file, it writes it to the order_models.yml file, which is not expected nor something I easily see how to fix without ending up copying and pasting the generated yml to the correct file
```
2. Deleting a custom test in model is not saved
- Reason for issue#1 is patch path is not overwritten when user switches models …
=> fix: save documentation in different yml s

src/services/deferToProdService.ts, src/webview_provider/insightsPanel.ts
Defer to prod settings is not saved properly in windows machine
Uri.parse does not resolve the projectRoot to right project, because of this the right project is not found to save the config. Updated to use Uri.file which can resolve to right project and config is saved
NA
- Enable/disable defer for a project in actions panel in windows and mac machine
- should be able to save the config
=> fix: defer for windows

src/dbt_client/dbtCoreIntegration.ts
Projects without defer setup is failing to initialize
Added error handler to avoid throwing error in extension startup
=> fix: defer error on project load

src/commands/bigQueryCostEstimate.ts, src/dbt_client/dbtIntegration.ts, src/dbt_client/dbtTerminal.ts, src/manifest/pythonEnvironment.ts
have to print env vars twice to display 
adding delay between showing and writing to terminal
=> fix: have to print env vars twice to display anything

.vscode/launch.json, dbt_core_integration.py, src/content_provider/sqlPreviewContentProvider.ts, src/manifest/dbtProject.ts
Fixes #1027
Ensure the project is initialized again when the project is parsed in order to capture changes in configuration and ensure parsing takes them into account.
- SQL Preview a dbt model
- Make a change to the profile eg schema, database, ...
- Change the dbt model
- The profile changes should be reflected in SQL preview
=> Fix compilation preview when profile changes

src/dbt_client/dbtCloudIntegration.ts
Not able to setup external executor project in windows
dbt path was not found and fix was added to find dbt.exe file in the python venv
- Setup a dbt project with venv in windows
- should be able to run all actions without any issue
=> fix: dbt path from python venv in windows

src/autocompletion_provider/modelAutocompletionProvider.ts, src/utils.ts
https://github.com/AltimateAI/vscode-dbt-power-user/issues/301
https://github.com/AltimateAI/vscode-dbt-power-user/issues/804
Relevant vscode issue: https://github.com/microsoft/vscode/issues/24464
For debugging, might have to add in `.vscode/settings.json`
```
"editor.quickSuggestions": {
"comments": false,
"strings": true,
"other": true,
}
```
Cases:
- type out `{{ ref('` and then autocomplete a model name or package name and model name
- type out `{{ ref("` and then autocomplete a model name or package name and model name
- type out `{{ ref(` and then autocomplete a model name or package name and model name
- type out `{{ ref(some_text` and then autocomplete a model name or package name and model name
- type out `{{ ref('packageName', '` and then autocomplete a model name for relevant …
=> fix: autocomplete

package.json, src/altimate.ts
To release dbt docs collaboration, enable the feature flag by default
Updated the defauly config value
- Load the extension
- should be able to see the comments panel and should be able to add comments without enabling collaboration
=> chore: make dbt docs collaboration enabled

src/manifest/dbtProject.ts, src/webview_provider/insightsPanel.ts, webview_panels/src/modules/healthCheck/ProjectHealthChecker.tsx
in project healthcheck, run all scan errors out at the start. 
file required was not properly handled for run all scan. now in case of run all checks, assuming manifest and catalog both are required.
=> fix: run all scan in project healthcheck

package.json, src/altimate.ts, src/services/docGenService.ts, src/webview_provider/datapilotPanel.ts, src/webview_provider/docsEditPanel.ts, src/webview_provider/newDocsGenPanel.ts, webview_panels/src/modules/dataPilot/components/common/DatapilotChatFollowup.tsx, webview_panels/src/modules/dataPilot/components/docGen/NewGenerationResults.tsx, webview_panels/src/modules/defer/ManifestSelection.tsx, webview_panels/src/modules/defer/defer.module.scss, webview_panels/src/modules/insights/Insights.tsx
Legacy documentation editor is not supported anymore
Remove the option to switch between legacy and new documentation editor
- Open a model in dbt project
- should be able to see only new documentation editor with bulk generate options
- in vscode settings also, user should not be able to switch to legacy doc editor panel
=> chore: remove legacy documentation editor support

src/services/fileService.ts
Query translate is not working in windows
Use Uri.file instead of Uri.parse
- Open a model and select piece of code 
- right click -> datapilot -> query translate
- select dialects
- click translate
- should not throw error and should be able to translate
=> fix: windows file uri for query translate

src/altimate.ts, src/exceptions/executionsExhaustedException.ts, src/exceptions/index.ts
- If user has exhausted execution limit in backend, 402 payment required error is thrown. Extension is not handling the error.
- Update the fetch and fetchAsStream API methods to show right error message
- exhaust your allowed limit per month
- try to run an execution, for ex: generate a doc
- should see the error with saas ui link
=> fix: pricing error handling

dbt_core_integration.py, package.json
dbt core 1.8 requires REQUIRE_RESOURCE_NAMES_WITHOUT_SPACES to be set in the args https://github.com/dbt-labs/dbt-core/blob/v1.8.0rc2/core/dbt/parser/manifest.py#L641. 
We are injecting the variable using environment variables and defaulting it to True
- Setup project with dbt 1.8
- Extension should work without any proble,,s
=> fix: for dbt 1.8, capability to use REQUIRE_RESOURCE_NAMES_WITHOUT_SPACES as env

src/dbt_client/dbtCoreIntegration.ts
Too many api to calls to `defer_to_prod_event`
Reposition event logging within a function dedicated exclusively to command execution.
=> fix: defer to prod event logging

src/commands/sqlToModel.ts, src/dbt_client/dbtCloudIntegration.ts, src/dbt_client/dbtCoreIntegration.ts, src/dbt_client/dbtIntegration.ts, src/manifest/dbtProject.ts
=> Throw diagnostics error if available for sql to model

new_lineage_panel/src/App.tsx, new_lineage_panel/src/CustomNodes.tsx, new_lineage_panel/src/service.ts, src/commands/tests/missingSchemaTest.ts, src/commands/tests/scanContext.ts, src/commands/tests/undocumentedModelColumnTest.ts, src/commands/tests/unmaterializedModelTest.ts, src/definition_provider/macroDefinitionProvider.ts, src/definition_provider/modelDefinitionProvider.ts, src/definition_provider/sourceDefinitionProvider.ts, src/domain.ts, src/manifest/parsers/nodeParser.ts, src/services/dbtTestService.ts, src/webview_provider/newDocsGenPanel.ts, webview_panels/src/modules/documentationEditor/components/tests/DbtTestCode.tsx, webview_panels/src/modules/documentationEditor/components/tests/hooks/useTestFormSave.ts, webview_panels/src/modules/documentationEditor/components/tests/utils.ts, webview_panels/src/modules/documentationEditor/state/types.ts
Packages folder is not downloaded on dbt cloud, so we can't resolve the path to any dbt entities located there.
Make path optional
=> Make path optional

src/services/docGenService.ts, src/webview_provider/docsEditPanel.ts
If vscode workspace contains multiple projects, and if user modifies documentation of a model in a project and switched to another model in another project, the save alert warning message shows up. but the save is not working
- This is mainly because of getting project by current active open file.
- Modified code to send filePath along with documentation data and use that to find project and save the data
- Open a workspace with multi project setup
- modify documentation of a model in a project
- without saving, open another file from another project
- in the warning message, click save changes
- modified documentation should be saved to right model in right project
=> fix: save alert when switching in multi project

src/services/dbtTestService.ts, src/services/docGenService.ts, src/services/queryAnalysisService.ts, src/webview_provider/altimateWebviewProvider.ts, src/webview_provider/datapilotPanel.ts, src/webview_provider/docsEditPanel.ts, src/webview_provider/newDocsGenPanel.ts, webview_panels/src/modules/documentationEditor/DocumentationEditor.tsx, webview_panels/src/modules/documentationEditor/DocumentationProvider.tsx, webview_panels/src/modules/documentationEditor/components/help/DocumentationHelpContent.tsx, webview_panels/src/modules/documentationEditor/state/documentationSlice.ts, webview_panels/src/modules/documentationEditor/state/types.ts
- We cannot display documentation editor if there is any error in project or active open file is not a model. So it is confusing for the user to know what is the reason for not showing documentation of model
- Show warning message if the open file is not valid model
- show error message if there is any error in project and a button to view problems tab
https://www.loom.com/share/b8f5ca6ac24a460690af485830c50723?sid=03fb89e1-9b7a-4601-8f3e-e075fb19c746
- open a schema.yml file
- should see warning message
- delete the profile for the project, delete the target directory
- on refresh should see the error message with button
=> fix: add guards for doc editor

webview_panels/src/modules/queryPanel/components/perspective/PerspectiveViewer.tsx, webview_panels/src/modules/queryPanel/components/perspective/perspective.scss
New query results view does not allow user to select contents of cells in table
Enabled text select for cells
- Run a query and open query results panel
- try to select the text in the gird
- user should be able to select the text
=> fix: query results copy from cell issue

src/dbt_client/dbtCoreIntegration.ts, src/telemetry/index.ts
Need an attribute for all telemetry events when dbt-loom is installed for dbt core project
Added custom attributes in telemetry service
- Setup [dbt-loom-example](https://github.com/Bl3f/dbt-loom-example) project
- Any telemetry event sent after project initialization should have `dbtLoomInstalled` attribute as `true`
=> fix: add telemetry attribute for dbt-loom

src/manifest/parsers/testParser.ts
Doc editor does not display tests for quoted columns
In manifest, quoted column name are stored with extra quotes for tests. So, modified testParser to remove extra quotes
- create quoted column
- add tests in schema.yml
- doc editor should show the tests
=> fix: render tests for quoted column names

src/services/dbtTestService.ts, src/utils.ts, src/webview_provider/docsEditPanel.ts
If a column has same type of generic test with diff config, doc editor does not save properly
- While finding the config of the test from existing schema, equate the values to get right config
- add test as in issue #1219 for any column in dbt project
- change some description of model from doc editor
- save
- should save with right config
=> fix: find right config if same dbt test is added with diff configs in yml

new_lineage_panel/src/components/styles.module.scss, new_lineage_panel/src/utils.ts
Lineage legend has duplicate `Non Select` and should show dashed border
removed duplicate entry and fixed css
- Open a dbt model
- go to lineage panel
- should see lineage legend with above fixes
=> fix: lineage legend UI

src/webview_provider/docsEditPanel.ts
If schema.yml has entry only for model and no columns, then getting below error 
```
TypeError: Cannot read properties of undefined (reading 'find')
```
use default array if columns are not added in schema.yml
- in schema.yml, create a model without columns
- sync with db from doc editor
- should not see any error
=> fix: find error when modifying column names

src/webview_provider/altimateWebviewProvider.ts, src/webview_provider/queryResultPanel.ts, webview_panels/src/main.scss, webview_panels/src/modules/newFeature/NewFeatureIndicator.tsx, webview_panels/src/modules/queryPanel/components/openInTabButton/OpenInTabButton.tsx, webview_panels/src/uiCore/components/tooltip/Tooltip.tsx
New features are not highlighted
Add new feature indicator, in this case for `Open in Tab` button in query results panel
- Execute a query and in query results panel, open in tab button should have red indictor
=> fix: add new feature indicator to open in tab button

new_lineage_panel/src/CustomNodes.tsx, new_lineage_panel/src/graph.ts
There are state issue when performing column level lineage. 
First full expanding table lineage and performing column lineage on just that works correctly.
But first performing column lineage and then expanding table lineage, shows wrong type of edges(direct/indirect).
Move assigning edge type code from creation of new edges to merging of edges. 
=> fix: lineage state issues

webview_panels/src/modules/queryPanel/components/perspective/PerspectiveViewer.tsx
- white screen flashes when executing query
- Modified order of theme to take vintage as default, so we will not see flashing white screen
- use dark theme in vscode
- Open a dbt model
- execute query
- notice no white flashing screen before rendering results table
=> fix: flashing screen in query panel

src/code_lens_provider/virtualSqlCodeLensProvider.ts, src/commands/index.ts, src/dbtPowerUserExtension.ts, src/webview_provider/docsEditPanel.ts, src/webview_provider/queryResultPanel.ts, webview_panels/src/assets/icons/index.tsx, webview_panels/src/lib/altimate/altimate-components.d.ts, webview_panels/src/lib/altimate/main.js, webview_panels/src/modules/queryPanel/QueryPanelDefaultView.tsx, webview_panels/src/modules/queryPanel/components/queryPanelBookmarks/BookmarkPrivacySettingButton.tsx, webview_panels/src/modules/queryPanel/components/queryPanelBookmarks/QueryPanelBookmarks.tsx, webview_panels/src/modules/queryPanel/components/queryPanelQueryHistory/QueryPanelHistory.tsx, webview_panels/src/uiCore/components/codeblock/index.tsx, webview_panels/src/uiCore/components/iconButton/IconButton.tsx
- use `jinja-sql` language instead of `sql` to have jinja/dbt auto completions as well
- open editor with code from bookmarks/history tab
- fix saving doc editor, when new column with test is saved
- added message in welcome screen in query panel to help users to enable bookmarks feature
- toggle bookmark's privacy while opening share popup
=> fix: query bookmarks feedback changes

src/code_lens_provider/virtualSqlCodeLensProvider.ts, src/webview_provider/queryResultPanel.ts
- errors are shown in telemetry
- project selector codelens shows for all dbt related files
- add sanity check for optional objects for below errors
```
Cannot read properties of undefined (reading 'visible')
Cannot destructure property `code` of undefined
```
- updated condition to show project selector only for new query files
- open any existing dbt related files. Should not see project selector codelens
- Click `New Query` button in query results panel - should see project selector codelens
=> fix: telemetry errors

src/dbt_client/dbtCoreIntegration.ts
Error is thrown while executing limit query macro. Details: https://github.com/AltimateAI/vscode-dbt-power-user/pull/1320#issuecomment-2249057494
Pass right arguments
- Execute a query using poweruser execute button
- Compiled sql in query results panel should show query with limit
=> fix: get limit sub query macro

webview_panels/src/modules/queryPanel/components/QueryPanelContents/QueryPanelTitle.tsx, webview_panels/src/modules/queryPanel/components/queryPanelBookmarks/QueryPanelBookmarks.tsx
Users could not find bookmarks tab
highlight bookmarks tab
=> fix: highlight bookmark tab

webview_panels/src/modules/documentationEditor/DocumentationEditor.tsx, webview_panels/src/modules/documentationEditor/styles.module.scss
https://altimateai.atlassian.net/browse/AI-1863
In doc editor panel, currently width of the doc editor is fixed. In small screens, some of the space in right side is unused. Fixing that.
Changing the styles for doc editor
Change:
Before:
- run the extension with this branch
- open doc editor panel
- see if it fills the whole screen
=> feat: AI-1863-In-doc-editor-implement-auto-expandable-UI

dbt_core_integration.py
https://github.com/AltimateAI/vscode-dbt-power-user/issues/1340
I have a complicated dbt project requires specifying profile, target and vars explicitly on dbt-compile. So currently some features run dbt-compile (e.g. compiled sql preview, lineage) don't work.
Allow to provide these parameters via environment variables.
=> pass profile, target and vars via env vars

src/manifest/dbtProject.ts, src/webview_provider/altimateWebviewProvider.ts, webview_panels/src/modules/documentationEditor/components/tests/forms/AcceptedValues.tsx
When getting distinct column values for adding accepted_values test, if there is an error, it is not shown to user.
Show error message on failure
- Open a dbt cloud project which could throw error while getting distinct column values from db
- Try to add accepted_values test and click get distinct column values
- If any error happens, error should be shown
=> fix: show error on failure while getting distinct column values
