- package-lock.json
- package.json
- src/definition_provider/macroDefinitionProvider.ts
> added support for macro lookup in external packages

- src/definition_provider/sourceDefinitionProvider.ts
> added support for source definition lookup

- src/autocompletion_provider/autocompletionProviderFactory.ts
- src/autocompletion_provider/macroAutocompletionProvider.ts
- src/autocompletion_provider/modelAutocompletionProvider.ts
- src/autocompletion_provider/sourceAutocompletionProvider.ts
- src/commands/runModel.ts
- src/custom.d.ts
- src/dbtManifest.ts
- src/definition_provider/definitionProviderFactory.ts
- src/definition_provider/macroDefinitionProvider.ts
- src/definition_provider/modelDefinitionProvider.ts
- src/definition_provider/sourceDefinitionProvider.ts
- src/domain.ts
- src/extension.ts
- src/manifestContainer.ts
- src/statusbar/runResultStatusBarProvider.ts
- src/statusbar/statusBarFactory.ts
- src/treeview_provider/ModelParentTreeviewProvider.ts
- src/treeview_provider/treeviewProviderFactory.ts
- src/utils.ts
> Add support for multiple workspacefolders

- package.json
- src/dbt_client/dbtCommandFactory.ts
Also provides a solution for #108
> Optional configuration value for custom profile dir

- query_panel/main.js
Resolves https://github.com/innoverio/vscode-dbt-power-user/issues/129
I have seen that linting automatically ran, I can reset the style if you see this as a problem to review the PR
> [Changed] Resize query panel table height on panel resize

- src/dbt_client/dbtTerminal.ts
> Remove Extra blank lines in cli output

- src/manifest/dbtProject.ts
Fixes #305
Didn't think these were necessary.
> fix #305: fix typo in environment error message

- src/code_lens_provider/sourceModelCreationCodeLensProvider.ts
- src/manifest/dbtProject.ts
> Generate model with table identifier

- package.json
Remove not working command declaration
> [Removed] Not working vscode command

- query_panel/index.html
- query_panel/main.js
resolves ##438
Added table scaler
> Added table scale field

- src/lineage_provider/modelGraphViewPanel.ts
- src/webview_view/queryResultPanel.ts
fix a few issues happening when sending data to a webview before it is live or when it is hidden. 
Fixes #333 , fixes perpetual loading status on query window when query view is loaded while hidden.
> Webview fix

- README.md
- package-lock.json
- package.json
- src/autocompletion_provider/docAutocompletionProvider.ts
- src/autocompletion_provider/macroAutocompletionProvider.ts
- src/autocompletion_provider/modelAutocompletionProvider.ts
- src/autocompletion_provider/sourceAutocompletionProvider.ts
- src/content_provider/sqlPreviewContentProvider.ts
- src/dbtPowerUserExtension.ts
- src/dbt_client/index.ts
- src/definition_provider/docDefinitionProvider.ts
- src/definition_provider/macroDefinitionProvider.ts
- src/definition_provider/modelDefinitionProvider.ts
- src/definition_provider/sourceDefinitionProvider.ts
- src/document_formatting_edit_provider/dbtDocumentFormattingEditProvider.ts
- src/inversify.config.ts
- src/manifest/dbtProject.ts
- src/manifest/dbtWorkspaceFolder.ts
- src/manifest/parsers/index.ts
- src/manifest/pythonEnvironment.ts
- src/telemetry/index.ts
- src/webview_view/queryResultPanel.ts
- webpack.config.js
> Implement telemetry

- README.md
> fix: remove url shortners from readme

- src/altimate.ts
- src/manifest/dbtProject.ts
- src/webview_provider/docsEditPanel.ts
> Use adapter type in model gen

- src/webview_provider/docsEditPanel.ts
- src/webview_provider/modelGraphViewPanel.ts
- src/webview_provider/queryResultPanel.ts
Add telemetry when a tab becomes active.
> feat: add telemetry event when you switch to a webview

- README.md
- [ x ] I have run this code and it appears to resolve the stated issue
- [ x ] `README.md` updated and added information about my change
> fix: update readme page links

- src/webview_provider/queryResultPanel.ts
resolves #571 #464 #428 
I had this issue in my environment, also. This fix resolved the issue. However, I am unsure why the existing code doesn't work and requires us to explicitly focus on the view. 
- [X ] I have run this code and it appears to resolve the stated issue
> fix: query panel switching issue

- query_panel/index.html
- query_panel/main.js
> feat: Download and Copy button added to the query results view

- new_lineage_panel/src/App.tsx
- new_lineage_panel/src/CustomNodes.tsx
- new_lineage_panel/src/service.ts
- new_lineage_panel/src/utils.ts
- src/domain.ts
- src/manifest/dbtWorkspaceFolder.ts
- src/webview_provider/lineagePanel.ts
- src/webview_provider/newLineagePanel.ts
- handling case insensitive column names
- change feedback form url for cll
- added parents node in cll processing
> fix: minor issues in column level lineage

- new_lineage_panel/src/App.tsx
feat: increase zoom out level for react flow
> feat: increase zoom out level for react flow

- package.json
- query_panel/assets/tabulator.min.css
- query_panel/assets/tabulator.min.js
- query_panel/index.html
- query_panel/main.js
- src/webview_provider/queryResultPanel.ts
> Feat: make query panel UX configurable

- dbt_integration.py
- query_panel/main.js
- src/manifest/dbtProject.ts
- src/webview_provider/queryResultPanel.ts
> Add schema to perspective

- dbt_integration.py
- package.json
- src/altimate.ts
- src/commands/index.ts
- src/commands/sqlToModel.ts
- src/domain.ts
- src/manifest/parsers/sourceParser.ts
> feat: Plain sql to model

- dbt_integration.py
should resolve #648.
nested named connections were opened with same name and potentially get closed before the outer context has finished execution. Alternate is having different named connections but better to prevent nesting since the inner calls can reuse the outer connection. This should fix the connection is closed errors we are seeing.
> fix: connection is closed errors

- src/manifest/dbtProject.ts
> fix: update err message

- dbt_integration.py
- query_panel/main.js
- disable number grouping
- better handling for int and floats
> fix: query panel number formatting

- src/manifest/dbtProject.ts
> Initialize metadata based on existing files

- new_lineage_panel/src/App.tsx
> fix: direct indirect links text

- dbt_integration.py
- new_lineage_panel/src/TableDetails.tsx
- new_lineage_panel/src/graph.ts
- new_lineage_panel/src/utils.ts
- src/webview_provider/newLineagePanel.ts
> Feat: lineage handle ephemeral nodes

- src/inversify.config.ts
- src/manifest/dbtProjectContainer.ts
- src/manifest/dbtWorkspaceFolder.ts
- src/quickpick/index.ts
- src/quickpick/projectQuickPick.ts
wait for projects to load before populating walkthrough items.
> fix: wait for projects to load.

- src/manifest/dbtProjectContainer.ts
> fix: state saving not working if someone ignored the walkthrough prompt

- package.json
- src/utils.ts
Display Name not working - vscode auto generates the name of the property based on the property text. cant seem to override using display name as in other places. if this request does get accepted, we might be able to do something.
This PR updates the description only.
> fix: AI-1119 updated desc of key/instance

- package.json
- query_panel/index.html
- query_panel/main.js
- src/altimate.ts
- src/commands/index.ts
- src/commands/runModel.ts
- src/manifest/dbtProject.ts
- src/manifest/dbtProjectContainer.ts
- src/webview_provider/queryResultPanel.ts
> feat: Query explanation

- src/webview_provider/docsEditPanel.ts
> Fix no columns present in yaml error

- dbt_integration.py
> fix: do not compile an already compiled node

- new_lineage_panel/src/TableDetails.tsx
- new_lineage_panel/src/service.ts
- src/manifest/dbtProject.ts
- src/manifest/dbtProjectContainer.ts
- src/manifest/parsers/graphParser.ts
- src/webview_provider/docsEditPanel.ts
- src/webview_provider/newLineagePanel.ts
> fix: handle source node

- package.nls.json
- src/commands/index.ts
- src/commands/walkthroughCommands.ts
- src/dbt_client/dbtCommandFactory.ts
- src/dbt_client/dbtVersionEvent.ts
- src/dbt_client/index.ts
- src/manifest/dbtProject.ts
- src/manifest/dbtProjectContainer.ts
- src/statusbar/versionStatusBar.ts
> Install dbt

- new_lineage_panel/src/App.tsx
- new_lineage_panel/src/CustomNodes.tsx
- new_lineage_panel/src/TableDetails.tsx
- new_lineage_panel/src/service.ts
- new_lineage_panel/src/styles.module.scss
- new_lineage_panel/src/utils.ts
- src/altimate.ts
- src/webview_provider/newLineagePanel.ts
> Fix: source cll

- package.json
- src/commands/index.ts
- src/commands/runModel.ts
- src/domain.ts
- src/manifest/dbtProjectContainer.ts
> command submenu

- new_lineage_panel/src/App.tsx
- new_lineage_panel/src/graph.ts
- src/commands/runModel.ts
- src/utils.ts
- src/webview_provider/newLineagePanel.ts
- src/webview_provider/queryResultPanel.ts
> fix: error messages and centering

- query_panel/index.html
> fix: text change

- query_panel/main.js
> fix: floating number formatting

- package.json
> updated package info

- package.json
- src/quickpick/sqlQuickPick.ts
- icon does not show if key is absent
- add sql to model in quick pick
- Fixes Icons for quick pick
> fix: icon not present

- new_lineage_panel/src/TableDetails.tsx
- src/altimate.ts
> fix: text for CLL preview

- src/quickpick/puQuickPick.ts
Point the documentation link to the docs site
> fix: documenation link

- new_lineage_panel/src/TableDetails.tsx
> fix: formatting text

- src/altimate.ts
> fix: signup text

- new_lineage_panel/src/App.tsx
- new_lineage_panel/src/TableDetails.tsx
- src/altimate.ts
- src/webview_provider/docsEditPanel.ts
- src/webview_provider/newLineagePanel.ts
- hide `Sync with DB` button for ephemeral
- flashing tooltip in select/non-select info button in cll
- disallow column selection for ephemeral
- better error message around credentials
> Minor fixes

- src/altimate.ts
- src/telemetry/index.ts
> adding network logs

- src/altimate.ts
> fix: message

- altimate_packages/altimate/utils.py
- altimate_packages/altimate/validate_sql.py
> fix: validate sql error messages and improvements

- src/altimate.ts
- src/dbtPowerUserExtension.ts
- src/manifest/dbtProjectContainer.ts
- src/validation_provider/index.ts
> Credentials validation

- src/manifest/dbtWorkspaceFolder.ts
> Fix allowListFolders

- src/commandProcessExecution.ts
- src/commands/walkthroughCommands.ts
- src/dbt_client/dbtCoreIntegration.ts
- src/dbt_client/dbtIntegration.ts
- src/inversify.config.ts
- src/manifest/dbtProject.ts
> feat: returning the result instead of logging in terminal

- .github/workflows/ci.yml
- Enables CI to publish pre release version of extension
- Tested the flow in this repo: https://github.com/AltimateAI/release-test/actions
> chore: pre release support

- new_lineage_panel/src/App.tsx
- new_lineage_panel/src/CustomNodes.tsx
- new_lineage_panel/src/TableDetails.tsx
> feat: adding test ids

- src/dbt_client/dbtIntegration.ts
> Use Python raw string

- package-lock.json
- package.json
> releasing 0.29.0

- dbt_integration.py
- src/commands/tests/staleModelColumnTest.ts
- src/dbt_client/dbtCoreIntegration.ts
- src/manifest/modules/sourceFileWatchers.ts
- src/manifest/modules/targetWatchers.ts
- src/manifest/parsers/docParser.ts
- src/manifest/parsers/index.ts
- src/manifest/parsers/macroParser.ts
- src/manifest/parsers/nodeParser.ts
- src/manifest/parsers/sourceParser.ts
> Fix target watchers

- dbt_integration.py
- package.json
- src/dbt_client/dbtCoreIntegration.ts
- src/dbt_client/dbtIntegration.ts
- src/inversify.config.ts
- src/manifest/dbtWorkspaceFolder.ts
> Fix project discovery for large projects with multiple packages

- new_lineage_panel/src/CustomNodes.tsx
> fix: model name with spaces

- dbt_integration.py
- package.json
Fixes extension looking at packages which it should avoid.
Resolves #835
> fix: resolve paths for the packages nicely 

- src/manifest/parsers/macroParser.ts
> fix: macro go to definition

- query_panel/main.js
Clicking play button multiple times get s the timer to keep going up
> fix multiple click on run button

- dbt_integration.py
- package.json
> fix: python process exits when unhandled exception exists

- src/webview_provider/docsEditPanel.ts
> Fix missing type when synching columns

- dbt_integration.py
- src/dbt_client/dbtCoreIntegration.ts
- src/manifest/dbtProject.ts
> Load in-memory manifest asap

- new_lineage_panel/src/Demo.tsx
Add missing documentation link
> fix: missing doc link

- package.json
> fix: change title for lineage

- src/autocompletion_provider/modelAutocompletionProvider.ts
- src/domain.ts
- src/manifest/parsers/nodeParser.ts
Analysis nodes should not appear in auto-complete
Example:
resolves [AI-1448](https://altimateai.atlassian.net/browse/AI-1448)
[AI-1448]: https://altimateai.atlassian.net/browse/AI-1448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: don't show analysis nodes in autocomplete

- src/dbt_client/dbtTerminal.ts
- src/dbt_client/exception.ts
- src/webview_provider/docsEditPanel.ts
- added logging service in dbt terminal 
- central place for logging, telemetry and showing error messages to user
> Feat logging service

- package.json
> chore: bump 0.30.1

- .github/workflows/ci.yml
- package.json
> fix: webview panels release from GHA

- dbt_integration.py
- package.json
- src/dbt_client/dbtCoreIntegration.ts
- env variables set
- profiles
- target
> feat: ENV extension basic changes

- webview_panels/src/modules/commonActionButtons/CommonActionButtons.tsx
> fix: feedback link

- new_lineage_panel/src/App.tsx
- new_lineage_panel/src/CustomNodes.tsx
- new_lineage_panel/src/Demo.tsx
- new_lineage_panel/src/Feedback.tsx
- new_lineage_panel/src/Help.tsx
- new_lineage_panel/src/TableDetails.tsx
- new_lineage_panel/src/graph.ts
- new_lineage_panel/src/service.ts
- new_lineage_panel/src/service_utils.ts
- new_lineage_panel/src/utils.ts
- src/altimate.ts
- src/webview_provider/newLineagePanel.ts
Support for column lineage cancellation
- added cancel in progress notification when doing column lineage
- cancel ongoing column lineage on cancel button(progress notif), reset button and show old ui
- disable select/non-select button, table expand button, clicking on another column when column lineage is ongoing
> feat: lineage cancellation

- dbt_integration.py
- package.json
- src/dbt_client/dbtCoreIntegration.ts
Reverts AltimateAI/vscode-dbt-power-user#874
> Revert "feat: ENV extension basic changes"

- query_panel/main.js
Show the analytics options by default after successful query execution
> feat: show the analysis options by default.

- dbt_integration.py
- package.json
- src/dbt_client/dbtCoreIntegration.ts
> Feat/target path profiles dir 

- new_lineage_panel/src/CustomNodes.tsx
- new_lineage_panel/src/graph.ts
- new_lineage_panel/src/utils.ts
WIP
chore: code refactor
WIP
chore: code refactor
fix: overlap issue
WIP
chore: code refactor
chore: code refactor
chore: code refactor
WIP
WIP
WIP
WIP
WIP
> feat: lineage layout improvements

- src/dbt_client/dbtCoreIntegration.ts
> Fix profiles dir

- query_panel/index.html
> fix: query panel horizontal scrolling issue

- package.json
- src/services/queryAnalysisService.ts
- webview_panels/src/main.css
- webview_panels/src/modules/app/AppProvider.tsx
- webview_panels/src/modules/app/appSlice.ts
- webview_panels/src/modules/app/types.ts
- webview_panels/src/modules/app/useListeners.ts
- webview_panels/src/modules/dataPilot/components/queryAnalysis/QueryAnalysisActionButton.tsx
- webview_panels/src/modules/dataPilot/components/queryAnalysis/QueryAnalysisResult.tsx
- webview_panels/src/modules/dataPilot/datapilot.module.scss
- webview_panels/src/modules/documentationEditor/components/docGenerator/BulkGenerateButton.tsx
- webview_panels/src/modules/markdown/Renderer.tsx
- webview_panels/src/modules/markdown/markdown.module.scss
- webview_panels/src/testUtils/datapilot/queryAnalysis.ts
- webview_panels/src/uiCore/components/codeblock/codeblock.module.scss
- webview_panels/src/uiCore/components/codeblock/index.tsx
Fixes following issues
- compile sql for followup api request
- icons (ask followup qn submit button, sync with database refresh icon) colors fix
- apply theme for markdown renderer based on current vscode theme
- wrap the followup qns button
> fix: query analysis ux issues

- package.json
> removed datapilot related shortcuts

- src/services/docGenService.ts
- src/webview_provider/datapilotPanel.ts
- webview_panels/.storybook/main.ts
- webview_panels/src/main.css
- webview_panels/src/modules/app/requestExecutor.ts
- webview_panels/src/modules/commonActionButtons/CommonActionButtons.tsx
- webview_panels/src/modules/dataPilot/DefaultDatapilotView.tsx
- webview_panels/src/modules/dataPilot/components/queryAnalysis/QueryAnalysis.stories.tsx
- webview_panels/src/modules/dataPilot/components/queryAnalysis/QueryAnalysisActionButton.tsx
- webview_panels/src/modules/dataPilot/components/queryAnalysis/QueryAnalysisResult.tsx
- webview_panels/src/modules/dataPilot/components/queryAnalysis/types.ts
- webview_panels/src/modules/feedback/ResultFeedbackButtons.tsx
- webview_panels/src/testUtils/datapilot/queryAnalysis.ts
- webview_panels/src/uiCore/components/codeblock/index.tsx
- webview_panels/tsconfig.json
- webview_panels/vite.config.ts
added following changes:
- close feedback form after submit
- modified markdown theme - uses solarized-dark and solarized-light themes now
- enter key button will submit followup request
- query change - do not show explain request when going via start chat -> query change
> fix: query analysis improvements

- query_panel/index.html
- query_panel/main.js
- query_panel/style.css
- src/dbt_client/dbtCoreIntegration.ts
- src/dbt_client/dbtIntegration.ts
- src/manifest/dbtProject.ts
- src/webview_provider/queryResultPanel.ts
> Support query cancellation

- src/dbt_client/dbtCoreIntegration.ts
> Fix query execution

- src/dbt_client/dbtCloudIntegration.ts
The show command needs to have limit set as the argument. Otherwise it always defaults to 5. If undefined or negative, I am not  passing the parameter. So, it will default to 5
> fix: limit needs to be an argument

- src/dbt_client/dbtCloudIntegration.ts
- src/dbt_client/dbtIntegration.ts
- src/inversify.config.ts
> Support python installation

- src/dbt_client/dbtCoreIntegration.ts
- src/manifest/dbtProject.ts
- src/manifest/dbtProjectContainer.ts
- src/manifest/dbtWorkspaceFolder.ts
- src/manifest/event/manifestCacheChangedEvent.ts
- src/statusbar/versionStatusBar.ts
> feat: add status loader for parsing manifest

- src/webview_provider/docsEditPanel.ts
- src/webview_provider/newLineagePanel.ts
> fix: error when logging in docEditPanel 

- src/commands/sqlToModel.ts
- added progress and success notification for sql to model
> fix: sql to model ux

- src/dbt_client/dbtCoreIntegration.ts
Read custom packages if python fails to do so
> feat: Custom packags

- src/altimate.ts
- src/commands/tests/initCatalog.ts
- src/commands/tests/scanContext.ts
- src/commands/validateSql.ts
- src/dbt_client/dbtCloudIntegration.ts
- src/dbt_client/dbtCoreIntegration.ts
- src/dbt_client/dbtIntegration.ts
- src/manifest/dbtProject.ts
- src/manifest/parsers/nodeParser.ts
- src/webview_provider/newLineagePanel.ts
- fix getCatalog for external executor
- added bulk schema fetch for both dbt core and external executor
- migrated lineage and validateSQL to bulk fetch schema
- abstracted out common code between lineage and validateSQL into dbtProject
> bulk fetch schema in dbt external executor

- src/dbt_client/dbtIntegration.ts
Show progress for dbt build progess. If we don't, any additional commands get put into the queue and user has no visibility of steps
> fix: show progress for dbt build project

- src/altimate.ts
- src/validation_provider/index.ts
- src/webview_provider/newLineagePanel.ts
> fix: error for lineage and invalid credentials

- package.json
> bumping version for pre-release

- README.md
- package.json
> bumping version for release

- src/dbt_client/dbtCoreIntegration.ts
Error message is not clear
Better error message
- Enable defer to prof without any config local or remote set
> fix: defer on with no config error message

- package.json
> releasing 0.35.3

- src/dbt_client/dbtCloudIntegration.ts
- fixing the `warning` text to filter warnings in dbt cloud
> chore: change warning check

- package-lock.json
- src/dbt_client/dbtCloudIntegration.ts
- src/dbt_client/dbtCoreIntegration.ts
- src/dbt_client/dbtIntegration.ts
- src/manifest/dbtProject.ts
- src/manifest/modules/sourceFileWatchers.ts
- src/quickpick/sqlQuickPick.ts
Trigger manifest refresh on seed changes
Fix for #999 
Include csv and seed directories in source file changed event
N/A
Add/Change/Remove seed files
> Trigger manifest refresh on seed changes

- src/manifest/dbtProject.ts
> fix: distinct column values

- new_lineage_panel/src/CustomNodes.tsx
- https://github.com/AltimateAI/vscode-dbt-power-user/pull/922 was merged incorrectly
> fix: merge issue

- new_lineage_panel/src/App.tsx
- new_lineage_panel/src/CustomNodes.tsx
- new_lineage_panel/src/MoreTables.tsx
- new_lineage_panel/src/Settings.tsx
- new_lineage_panel/src/TableDetails.tsx
- new_lineage_panel/src/graph.ts
- new_lineage_panel/src/service.ts
- new_lineage_panel/src/utils.ts
- package.json
- src/webview_provider/newLineagePanel.ts
Persisting the lineage settings in workspace configuration
> Feat: lineage settings persistence

- CONTRIBUTING.md
- README.md
comply with dbt community content guidelines
> comply with dbt community content guidelines

- src/webview_provider/docsEditPanel.ts
- webview_panels/src/modules/documentationEditor/components/saveDocumentation/SaveDocumentation.tsx
- webview_panels/src/modules/documentationEditor/components/tests/hooks/useTestFormSave.ts
- Tests generated by datapilot for dbt models is not getting inserted
- handle the new test insertion for models
- handle sql in tests directory, tests from external packages
https://www.loom.com/share/c4b3a892c6a74e6aade1061510c7902c?sid=2a3a4a86-2a97-424b-a0e2-060d567f20de
- Open a dbt model
- Open datapilot for generating test
- enter a prompt for which datapilot which can suggest test for model
- insert the test
- save it
- refresh vscode
- should see new tests
> fix: custom model test addition

- package.json
> added meta data to improve discoverability of the extension

- src/dbt_client/datapilot.ts
- src/webview_provider/insightsPanel.ts
> fix: dp changes

- src/content_provider/sqlPreviewContentProvider.ts
> feat: added loader for compile node

- src/commandProcessExecution.ts
- src/commands/walkthroughCommands.ts
- src/dbt_client/datapilot.ts
- src/dbt_client/dbtIntegration.ts
> Add more logging in executor

- src/comment_provider/conversationProvider.ts
- webview_panels/src/lib/altimate/main.js
> fix: share name

- src/content_provider/sqlPreviewContentProvider.ts
> Fix error message in sql preview

- webview_panels/src/assets/icons/index.tsx
- webview_panels/src/assets/icons/styles.css
- webview_panels/src/modules/healthCheck/ProjectHealthChecker.tsx
- Ability to scan everything in project governance https://github.com/AltimateAI/vscode-dbt-power-user/issues/1066
- Show loader for get configs api call
> fix: governance UI

- src/altimate.ts
- src/services/docGenService.ts
- src/telemetry/index.ts
> Add local mode config

- src/manifest/dbtProjectContainer.ts
Add the below in `.vscode/settings.json` to hide walkthrough on initial setup
{
...,
"dbt. hideWalkthrough": true,
}
> feat: added hide walkthrough settings

- package.json
- src/commands/index.ts
- src/dbt_client/dbtCloudIntegration.ts
- src/dbt_client/dbtCoreIntegration.ts
- src/dbt_client/dbtIntegration.ts
- src/dbt_client/dbtTerminal.ts
- src/dbt_client/index.ts
- src/manifest/dbtProject.ts
- src/utils.ts
added diagnostic command that analyzes the extension's environment and operations to find discrepancies or problems
> feat: adding diagnostic command

- new_lineage_panel/src/service_utils.ts
- src/commands/validateSql.ts
- src/dbt_client/dbtCloudIntegration.ts
- src/dbt_client/dbtCoreIntegration.ts
- src/dbt_client/dbtIntegration.ts
- src/manifest/dbtProject.ts
- src/webview_provider/newLineagePanel.ts
- fix cancellation issue in lineage
- added cancellation for validate sql
for lineage, panel is greyed out after cancelling for long running quest. Was using `Promise.all` to parallelize but due to python lock essentially request were serial.
> fix: cancellation issue

- src/dbt_client/dbtCloudIntegration.ts
> Add source

- package.json
- src/commands/index.ts
renamed troubleshoot to diagnostic
> renamed troubleshoot to diagnostic

- src/quickpick/puQuickPick.ts
- src/statusbar/versionStatusBar.ts
- Change Status bar to core
- Change Icon in quickPick
- [y] I have run this code and it appears to resolve the stated issue
- [y] `README.md` updated and added information about my change
> fix: dbt status bar for core

- dbt_core_integration.py
> fix: Writeable Manifest Import for defer to prod

- src/commands/index.ts
- src/manifest/dbtProject.ts
> feat: adding paths and dbt project file content in diagnostics

- src/content_provider/sqlPreviewContentProvider.ts
- src/dbt_client/dbtCoreIntegration.ts
> fix: adding defer log events for execute and compiled sql

- src/commands/walkthroughCommands.ts
- src/dbt_client/dbtCloudIntegration.ts
> Various fixes for dbt cloud

- package-lock.json
- package.json
- src/dbt_client/dbtCloudIntegration.ts
> Fix semver check

- src/dbt_client/dbtCloudIntegration.ts
> Fix sql execution

- dbt_core_integration.py
> Copy global_flags

- src/dbt_client/dbtCloudIntegration.ts
> Fetch compiled sql for cloud

- new_lineage_panel/src/ActionWidget.tsx
- new_lineage_panel/src/App.tsx
- src/webview_provider/newLineagePanel.ts
User could not understand why lineage is not showing in some cases
- Added a warning message to user to open a valid node to see lineage 
- Also if there is any error in project, show the error in lineage panel
https://www.loom.com/share/13522a7b28a34d7e89755410eab42495?sid=775dc7de-2b38-4293-95e8-8013f23a972a
- open a schema.yml file and open lineage panel
- should see warning message
- If project has any error, error will also be shown
> fix: guards for lineage panel

- webview_panels/src/modules/documentationEditor/DocumentationProvider.tsx
> fix: ts error

- src/dbt_client/dbtCoreIntegration.ts
> Ensure thread is ended

- src/altimate.ts
- src/services/docGenService.ts
- src/webview_provider/datapilotPanel.ts
- src/webview_provider/docsEditPanel.ts
Send the column Counts while getting the Doc Gen.
> feat: add counts while getting doc gen

- new_lineage_panel/src/ActionWidget.tsx
- new_lineage_panel/src/App.tsx
- new_lineage_panel/src/CustomNodes.tsx
- new_lineage_panel/src/TableDetails.tsx
- new_lineage_panel/src/graph.ts
- new_lineage_panel/src/service.ts
- src/webview_provider/newLineagePanel.ts
- Using `env.sessionId` which will have values like `2fcc86de-6267-4471-8e04-07904223158b1716315453561`. It changes on vscode restart.
- Remove previous `sessionId`
> fix: change session id for column lineage

- src/commands/index.ts
> fix: diagnostics missing content

- src/hover_provider/modelHoverProvider.ts
> Fix model Hover provider

- dbt_core_integration.py
- src/commands/bigQueryCostEstimate.ts
- src/commands/runModel.ts
- src/commands/validateSql.ts
- src/content_provider/sqlPreviewContentProvider.ts
- src/dbt_client/dbtCloudIntegration.ts
- src/dbt_client/dbtCoreIntegration.ts
- src/dbt_client/dbtIntegration.ts
- src/manifest/dbtProject.ts
- src/manifest/dbtProjectContainer.ts
Support compilation preview and query preview of incremental models
> Support incremental compilation

- src/commands/index.ts
- src/inversify.config.ts
- src/manifest/dbtProjectContainer.ts
- src/manifest/dbtWorkspaceFolder.ts
> Add more logging to discover projects

- dbt_core_integration.py
dbt-loom project shows error 
- filtered dependencies with runtime config as LoomRunnableConfig
NA
- Open dbt loom project
- Problems tab should not have any error
- Following actions should work: execute sql, compile sql, autocomplete external project ref, lineage with external node icon
> fix: dbt-loom dependency issue

- dbt_core_integration.py
> Check if node_info is dict

- webview_panels/src/modules/healthCheck/IssueList.tsx
- webview_panels/src/modules/healthCheck/healthcheck.module.scss
File names in project health check flowing out of the box
Adding a style
> Project governance files overflow

- new_lineage_panel/src/StaticLineage.tsx
- src/webview_provider/sqlLineagePanel.ts
- refactor sql lineage to use query manifest service
- change sql lineage layouting algo to cleaner implementation
> fix: sql lineage code refactor and layout algo update

- new_lineage_panel/src/CustomNodes.tsx
- new_lineage_panel/src/Modals.tsx
- src/altimate.ts
- src/webview_provider/newLineagePanel.ts
> feat: lineage v4

- new_lineage_panel/src/CustomNodes.tsx
- new_lineage_panel/src/Lineage.tsx
- new_lineage_panel/src/TableDetails.tsx
- new_lineage_panel/src/graph.ts
- new_lineage_panel/src/service.ts
- src/altimate.ts
- src/webview_provider/newLineagePanel.ts
- Fix column lineage generation for seed /ephemeral
- Indirect lineage flag is selected based on settings
> fix: lineage v4

- altimate_packages/altimate/fetch_schema.py
- altimate_packages/altimate/utils.py
- dbt_cloud_integration.py
- dbt_core_integration.py
- src/dbt_client/dbtCloudIntegration.ts
- src/dbt_client/dbtCoreIntegration.ts
- src/dbt_client/dbtIntegration.ts
- src/manifest/dbtProject.ts
- src/webview_provider/newLineagePanel.ts
Instead of every time going to db for schema, we first try generate schemas by parsing sql
> feat: schema fetching optimization

- webview_panels/src/modules/queryPanel/components/perspective/perspective.module.scss
- white screen flashes when executing query
- Modified css to apply right background 
- use dark theme in vscode
- Open a dbt model
- execute query
- notice no white flashing screen before rendering results table
> fix: flashing white screen in query panel

- new_lineage_panel/src/CustomNodes.tsx
- new_lineage_panel/src/components/Tooltip.tsx
- new_lineage_panel/src/components/styles.module.scss
- new_lineage_panel/src/index.css
- fix code block formatting
- added code block for op node tooltip
> fix: sql lineage code formatting issues

- package.json
dbt docs collab feature does frequent polling
Until we fix with right polling, increased the polling interval to 15 mins
> chore: increase polling interval to 15 mins

- webview_panels/src/modules/queryPanel/components/perspective/perspective.module.scss
> revert: flashing screen fix

- new_lineage_panel/src/CustomNodes.tsx
- new_lineage_panel/src/Lineage.tsx
- new_lineage_panel/src/Modals.tsx
- new_lineage_panel/src/StaticLineage.tsx
- new_lineage_panel/src/main.tsx
- src/altimate.ts
- src/webview_provider/sqlLineagePanel.ts
- sql lineage layout improvements
- clicking on op node, like filter, union, etc. will show popup for code
> feat: improved sql lineage layout

- package.json
- src/webview_provider/newLineagePanel.ts
- src/webview_provider/sqlLineagePanel.ts
> feat: settings indirect edges as false by default

- src/dbt_client/dbtCloudIntegration.ts
- src/dbt_client/dbtCoreIntegration.ts
- src/dbt_client/dbtIntegration.ts
- src/webview_provider/docsEditPanel.ts
- src/webview_provider/queryResultPanel.ts
- webview_panels/src/modules/queryPanel/QueryPanelDefaultView.tsx
- webview_panels/src/modules/queryPanel/components/queryPanelBookmarks/BookmarkAccordion.tsx
- webview_panels/src/modules/queryPanel/components/queryPanelBookmarks/QueryBookmarkRow.tsx
- webview_panels/src/modules/queryPanel/components/queryPanelQueryHistory/ExecuteQueryButton.tsx
- webview_panels/src/modules/queryPanel/components/queryPanelQueryHistory/QueryHistoryRow.tsx
- webview_panels/src/modules/queryPanel/context/types.ts
- webview_panels/src/testUtils/queryResults/index.ts
- use model name in virtual document file name
- remove contact us option in preview panel if bookmarks is enabled
- fixed error while opening new query file
- show user name in shared bookmarks row
- fix delete a test in dbt1.8 with data_tests format
> fix: query bookmarks feedback updates

- src/altimate.ts
- src/webview_provider/queryResultPanel.ts
- src/webview_provider/sqlLineagePanel.ts
- webview_panels/src/modules/lineage/LineageView.tsx
> fix: lineage components

- src/dbt_client/dbtCoreIntegration.ts
> Fix limit bug

- dbt_core_integration.py
- src/dbt_client/dbtCoreIntegration.ts
> Fix limit bug #2

- src/webview_provider/newLineagePanel.ts
- unable to get column lineage after first time due to incorrect merging of PRs
> hotfix: no compiled sql for target node issue

- package.json
- src/code_lens_provider/documentationCodeLensProvider.ts
- src/code_lens_provider/index.ts
- src/commands/index.ts
feat: added documentation code lens
[
](https://github.com/AltimateAI/vscode-dbt-power-user/issues/1292)
> feat: added documentation code lens

- package.json
Changing the display name of the extension and mention about cloud support as well
> changing extension display name 

- package.json
- src/webview_provider/queryResultPanel.ts
- webview_panels/src/modules/queryPanel/QueryPanelDefaultView.tsx
Release Query history and bookmarks feature
- updated extension config to make bookmarks feature enabled by default
- reduced history cache size to 10
- added documentation link 
> fix: release query bookmarks feature

- new_lineage_panel/src/Lineage.tsx
https://www.loom.com/share/e5b86fea77154574a99e7f7d64edc9a8
> feat: expanding lineage by default to settings level

- src/altimate.ts
- src/commands/index.ts
- src/dbt_client/dbtTerminal.ts
- checking if extension has connectivity with the backend by making an unauthorized api call
> feat: added api connectivity info in diagnostics

- src/dbt_client/dbtCloudIntegration.ts
> Fix json parsing

- src/dbt_client/dbtCloudIntegration.ts
- src/manifest/dbtProject.ts
- src/manifest/event/runResultsEvent.ts
- src/manifest/modules/targetWatchers.ts
> Make RunResultWatcher emit events

- src/webview_provider/newLineagePanel.ts
handling issue https://github.com/AltimateAI/vscode-dbt-power-user/issues/1239
> fix: lineage handle unknown error

- src/manifest/dbtProject.ts
> Remove semicolon in query

- webview_panels/src/modules/queryPanel/components/perspective/PerspectivePlugins.ts
- webview_panels/src/modules/queryPanel/components/perspective/perspective.scss
Issues with string truncation in perspective viewer grid
Added a custom way to handle it via the plugin so that truncation will happen based on the user-defined width of the columns.
[A picture is worth a thousand words. Please highlight the changes if applicable.](https://www.loom.com/share/547f854ea9294cf48d120705e893e357?sid=f02e2616-0440-4273-82cf-5e51821f4ab2)
> feat: Add adjustable column width for perspective viewer grid

- src/manifest/dbtProject.ts
> Don't create ProjectConfigChangedEvent if project is not valid

- src/dbt_client/dbtCloudIntegration.ts
- src/telemetry/index.ts
> Remove secrets from stacktrace and make less calls in background for cloud

- src/dbt_client/dbtCloudIntegration.ts
> Validate dbt cloud output for executeSQL

- webview_panels/src/modules/queryPanel/QueryPanelDefaultView.tsx
New Notebook feature
Add a note in query panel
> feat: new feature message

- webview_panels/.storybook/main.ts
- webview_panels/src/modules/documentationEditor/styles.module.scss
- webview_panels/src/modules/queryPanel/components/queryLimit/styles.module.scss
IN light mode, bulk generate dropdown and query limit input are not clear
Fix css to improve visibility
> fix: light mode ui for doc editor and query panel
